config/routes.rb
Rails.application.routes.draw do
  get 'relationships/followers'
  get 'relationships/following'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  devise_for :users

  root :to =>"homes#top"
  get "home/about"=>"homes#about"

  resources :books, only: [:index,:show,:edit,:create,:destroy,:update] do
    resources :post_comments, only: [:create, :destroy] #post_commentsコントローラのアクション
    resource :like, only: [:create, :destroy] #単数形にすると、/:idがURLに含まれなくなる。(いいね削除の際いいねのID必要ない為)
  end
  resources :users, only: [:index,:show,:edit,:update] do
    resource :relationships, only: [:create, :destroy]
    get "followers" => "relationships#followers", as: "followers"
    get "following" => "relationships#following", as: "following"
  end

  get "/search", to: "searches#search"

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :book

  validates :user_id, uniqueness: {scope: :book_id} #user_idとbook_idのペアが一意である（重複しない）状態に制限
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController

  def create
    @book = Book.find(params[:book_id])
    like = current_user.likes.new(book_id: @book.id)
    like.save
    # redirect_to books_path
  end

  def destroy
    @book = Book.find(params[:book_id])
    like = current_user.likes.find_by(book_id: @book.id)
    like.destroy
    # redirect_to books_path
  end

end

app/helpers/like_helper.rb
module LikeHelper
end

app/views/likes/_btn.html.erb
<% if book.liked_by?(current_user) %>
    <%= link_to book_like_path(book), method: :delete, remote: true do %>
      ♥<%= book.likes.count %>
    <% end %>
<% else %>
    <%= link_to book_like_path(book), method: :post, remote: true do %>
      ♡<%= book.likes.count %>
    <% end %>
<% end %>

app/views/likes/create.js.erb
$("#like_btn_<%= @book.id %>").html("<%= j(render 'likes/btn', book: @book) %>");

app/views/likes/destroy.js.erb
$("#like_btn_<%= @book.id %>").html("<%= j(render 'likes/btn', book: @book) %>");